### ISSUE TITLE
Ports not connecting

### ISSUE THREAD

**Issue by pmanojlovic** [ICRAR/EAGLE#422]
Hi, I'm expecting a type File output port from a File component to smoothly connect to a type File input port of a BashShellApp and I'm not sure if I'm doing it right.

Here's what I tried, with version 4.5.2 from the webapp:
- Create one of each File and BashShellApp components
- Delete the File's dummy input port
- Create an Application Argument for the BashShellApp
	- Id Text: ms_in
	- Display Text: ms in
	- Type: File
- Change its Field Type to an Input Port
- Create another Input Port:
	- Id Text: metadata
	- Display Text: metadata
	- Type: String
- Create an output port:
	- Id Text: ms_out
	- Display Text: ms out
	- Type: File
- Change the File component's dummy output port Type to File
- Attempt to connect the File's 'dummy' port to BashShellApp's 'ms in'
- It will only snap to end of the node visually, regardless of how close you drag over the destination port:
![image](https://user-images.githubusercontent.com/10542066/178368253-002ac9bd-d80c-494a-805f-5614d743d17a.png)

- When inspecting the edge attributes the 'To Port' field is empty:
![image](https://user-images.githubusercontent.com/10542066/178368278-ef721cec-318f-4c45-bc44-de4c6fca5fae.png)

- And when editing To Port and manually selecting ms_in, a prompt states 'Error: Invalid Edge'

This minimum working example can be found here:
[ports_mwe.graph.zip](https://github.com/ICRAR/EAGLE/files/9087910/ports_mwe.graph.zip)

Have I set this up correctly? Are 'DALiuGE Components' and 'Raw Components' compatible? Is this a bug or is there a different way to approach this?

**Comment by awicenec** [comment]
Thanks for this issue report. Unfortunately I can't reproduce this with the steps you have
described. I have seen this effect before as well, but was not able to put my finger on it either.
We'll need to dig into this. Which browser/version are you using?

**Comment by pmanojlovic** [comment]
I've tested on EAGLE 4.5.2 from the webapp at [ICRAR](http://eagle.icrar.org) with Chrome (102.0.5005.115), Firefox (102.0.1), and Safari.

**Comment by alxndrwllmsn** [comment]
Hi, I have managed to reproduce the error. There are currently two ways (that I know of) of creating ports on components. You can either create them as Application Arguments and then edit them to change them to ports, or you can open the Component Parameters Table and use the Add Parameter button, setting the "Use As" property to Input/Output Ports. The former produces the effect described above (and below) and the latter produces ports that behave as expected. I have described each process below:

### Application Arg Method
If you create the ports by first creating them as Application Arguments using add button on the side panel:
![image](https://user-images.githubusercontent.com/11086385/178867952-fb01c7a6-106a-4615-992b-403e529cf280.png)
And then Editing them via the edit buttons in this panel:
![image](https://user-images.githubusercontent.com/11086385/178868068-cadd8806-37ce-44aa-afbd-dadb51544512.png)
And changing them from Application Arguments to Input/OutputPorts:
![Screen Shot 2022-07-14 at 9 35 19 am](https://user-images.githubusercontent.com/11086385/178868361-e01e6935-2d1b-4e28-8e94-e28f7f9ad72b.png)
This creates ports that connect weirdly with no Id's:
![image](https://user-images.githubusercontent.com/11086385/178868521-13f96cc7-573f-4177-a53e-598eab08aee6.png)
![Screen Shot 2022-07-14 at 9 38 53 am](https://user-images.githubusercontent.com/11086385/178868710-52d0035e-2903-4ec7-bd04-6480dfc3c4b3.png)

### Component Par Table Method
However, If you create the ports directly through the Component Parameters Table:
![image](https://user-images.githubusercontent.com/11086385/178868938-ce017657-5fde-47cd-844d-9009eca6e8b7.png)
![image](https://user-images.githubusercontent.com/11086385/178869006-b06b9e1f-9ef0-47b2-b720-feaa47442d5a.png)
It creates ports that connect correctly, and have Id's:
![image](https://user-images.githubusercontent.com/11086385/178869100-17c46b99-6fca-44f0-bbf7-e43af0521d7a.png)
![Screen Shot 2022-07-14 at 9 43 06 am](https://user-images.githubusercontent.com/11086385/178869168-06d76855-d3c6-4e6d-bd97-a949d5c5da28.png)

I hope this helps.

**Comment by pmanojlovic** [comment]
Thanks Alex, the component table method works well and is faster than clicking through the application argument menus. I'm still seeing the edge 'connect' to the end of the node visually but it has the correct port IDs.

![image](https://user-images.githubusercontent.com/10542066/178887913-d1a38ac6-4097-48a0-9f30-980a63666e7d.png)

**Comment by awicenec** [comment]
Hi Pero,

as a workaround, right now I guess it is best to only use the table to add ports, parameters or
arguments. That seems to work fine. I would also recommend to delete that output port and re-create
it using the table. That fixed the problem, at least for me.

Cheers,
Andreas

**Comment by james-strauss-uwa** [comment]
Thanks for the thorough investigation Alex and Pero, the screenshots and reproduction steps are much appreciated.

You are correct that when you add a new port via the '+' button, the arguments are added with empty string ids. This is a bug. It then also manifests itself as an error in the graph display, where an edge is drawn incorrectly, between the wrong ports.

I've made some fixes in a branch (eagle-814) and they should make it into the next version.

Thanks again.

**Comment by james-strauss-uwa** [comment]
We've deployed v4.5.5 to https://eagle.icrar.org and this issue is fixed.
