### ISSUE TITLE
Adding ports is unintuitive

### ISSUE THREAD

**Issue by pmanojlovic** [ICRAR/EAGLE#423]
There should be a shortcut to add ports with a [ + ] button like under Application Arguments.

Currently, in v4.5.2, you need to add an Application Argument and then edit it again to see and change the Field Type to InputPort/OutputPort.

It took a little while to find this after digging through the menus, and won't be clear to new users.

**Comment by james-strauss-uwa** [comment]
I agree, adding a '+' button to the input ports and output ports sections would be much easier, and would save a few clicks.

Actually, we have a task for it on JIRA (EAGLE-737), but I'll bump it up in priority.

Thanks.

**Comment by james-strauss-uwa** [comment]
We've deployed v4.5.5 to eagle.icrar.org, and it has '+' buttons at the bottom of the "input ports" and "output ports" sections.
