### ISSUE TITLE
Inconsistency in read-only state between side panel and parameter table

### ISSUE THREAD

**Issue by alxndrwllmsn** [ICRAR/EAGLE#431]
In the effort of making my graph usable for others, I've started to set some parameters to read-only.

I've noticed that when doing this, and setting component editing off in settings, the parameter table shows the parameter as editable, but the side panel has the parameter greyed out. See the images below:

Parameter table:
![Screen Shot 2022-08-08 at 12 01 16 pm](https://user-images.githubusercontent.com/11086385/183344734-2c43e6c8-3e37-4a4f-8fb2-e80062c5c6cd.png)

Side Panel:
![Screen Shot 2022-08-08 at 12 57 20 pm](https://user-images.githubusercontent.com/11086385/183344779-8fcbdedb-ba09-461d-9528-f8f981798774.png)

If needed the graph can be found [here](https://github.com/alxndrwllmsn/EAGLE-graph-repo/tree/master/dingo/dstack). The component in question is the "Create Parset" component on the left.

**Comment by james-strauss-uwa** [comment]
Thanks Alex. I can reproduce this, I've started a JIRA issue #822

https://icrar.atlassian.net/browse/EAGLE-822

**Comment by james-strauss-uwa** [comment]
![Screen Shot 2022-08-08 at 3 05 56 pm](https://user-images.githubusercontent.com/51597085/183362893-39847ae1-7aac-4e08-ad1b-d84d3979003d.png)

I've fixed the side panel so that it uses the correct 'readonly' attribute values. I've pushed the changes to master.
