### ISSUE TITLE
Enhancement - Infer `dropclass` parameter for legacy LGTs

### ISSUE THREAD

**Issue by myxie** [ICRAR/EAGLE#673]
# Summary
There was a change at some point that has made certain parameters required, including the `dropclass` for every drop: 

![image](https://github.com/ICRAR/EAGLE/assets/5227425/f601c023-af23-4a86-a10d-5bec2d8c50aa)

These are not 'fixable' so require manual intervention to get the graph to translate for a number of historical graphs (e.g. most of the SDP Pipelines in EAGLE-test-repo).

# Proposed Solution
It would be great to have the "Fix all" button also address this issue, at least for the `dropclass` component, but I suspect it could also do the `num_cpus` field as well. 

For the application drops, it looks like there used to be an `appclass` parameter, so perhaps that could be renamed to `dropclass`? I don't see an exposed `dataclass` parameter for data drops, so that may be more difficult.

**Comment by james-strauss-uwa** [comment]
Yes, sounds good. We should add a "fix function" for missing required fields.

At the very least we can add a parameter with reasonable defaults. But, as you say, we could map a few old parameter names to new parameters. For example "appclass" -> "dropclass".

If we add a "fix function" for the missing field, it will be run as part of "Fix All"

I'll create a ticket in JIRA for this

**Comment by james-strauss-uwa** [comment]
https://icrar.atlassian.net/jira/software/c/projects/EAGLE/issues/EAGLE-1214

**Comment by james-strauss-uwa** [comment]
I've merged a fix into master.

**Comment by james-strauss-uwa** [comment]
v6.4.2 has been deployed with a "fix function" for these missing fields.
