### ISSUE TITLE
`docker-compose` no longer recommended install option

### ISSUE THREAD

**Issue by myxie** [ICRAR/EAGLE#721]
# Issue

`build_eagle.sh` uses the `docker-compose` command for setting up EAGLE on a local machine. It looks like this has been deprecated in favour of `docker compose`: https://docs.docker.com/compose/install/. For newer installs/users of docker/EAGLE, this will break the build script. 

# Potential solution 

It's trivial to fix this locally (just remove the hyphen in favour of a space) so isn't high priority.
If we want to change this in the long run, for backwards compatibility we could check if `docker-compose` exists and change the command accordingly: 

```bash
DOCKER = "docker-compose"

if ! command -v DOCKER
then
    DOCKER = "docker compose"
fi
```

**Comment by james-strauss-uwa** [comment]
That's interesting, we've also run into this problem with SKA work recently. I seem to have the latest docker and ran into the problem of missing `docker-compose`, requiring `docker compose` instead. But the others in the team, on a mix of platforms (linux, mac intel, mac arm) etc, all still have `docker-compose`.

I think your solution for backwards compatibility looks great. Would you be happy to add a pull request?

**Comment by myxie** [comment]
@james-strauss-uwa it is odd that it the change kind of just skated by unannounced and irregularly. At any rate, I've got a PR up at #722 for you whenever you're free.
