### ISSUE TITLE
Error opening saved EAGLE Logical Graph

### ISSUE THREAD

**Issue by myxie** [ICRAR/EAGLE#8]
I created the attached graph in July, and have tried to open it again in the Editor at https://eagle.icrar.org/.  

However, when attempting to use the 'Load Graph' option in the GUI, the graph is not opened in the editor. I have successfully opened other graphs. 

This graph (SDPContinuumPipelineNoOuter) appears to be a valid DALiuGE LG, as I am able to translate it using the dlg_translator code. 

Any indications as to what may have changed in the LG Editor would be greatly appreciated!

[SDPContinuumPipelineNoOuter.txt](https://github.com/ICRAR/EAGLE/files/5325636/SDPContinuumPipelineNoOuter.txt)

**Comment by myxie** [comment]
This may have something to do with a change in EAGLE which has modified the `category` variable? 

An old (working) .graph file that loads and translates is as follows: 

```json
            "canHaveInputs": true,
            "canHaveOutputs": true,
            "category": "Component",
            "categoryType": "Application",
            "collapsed": false,
            "colour": "#3498DB",
            "description": "An application component in the form of a Python app",
            "drawOrderHint": 0,
            "exitAppName": "",
            "fields": [...
```

A newer graph, that is created in EAGLE and can be reloaded, but fails to translate due to PythonApp not being an allowed category in DALIUGE: 

```json
            "canHaveInputs": true,
            "canHaveOutputs": true,
            "category": "Component",
            "categoryType": "Application",
            "collapsed": false,
            "colour": "#3498DB",
            "description": "An application component in the form of a Python app",
            "drawOrderHint": 0,
            "exitAppName": "",
            "fields": [...
```

**Comment by james-strauss-uwa** [comment]
Sorry I missed this issue, somehow I didn't receive a notification.

You're correct, we moved from the term "Component" to "PythonApp". I hope it didn't cause you too much trouble.

The attached graph seems to load in the current version of EAGLE.
